[package]
name = "currency_utils"
version = "0.1.0"
authors = ["Javed Nissar <javednissar@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty-money = "0.3.6"
anyhow = "1.0.37"
thiserror = "1.0"